# имя workflow
name: GitHub Actions CI demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# триггер запуска (1 - при вливании в master, 2 - открыт pull request в master, 3 - вручную)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# этапы workflow - они же джобы
jobs:
  ci-demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from ci-demo workflow!"
